# Generated by Django 3.0.6 on 2020-05-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_webform', '0002_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='description',
            new_name='word_to_search',
        ),
        migrations.AddField(
            model_name='document',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
